version: 1.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install -r requirements.txt -q
      - cfn-lint -v
  build:
    commands:
      - sh buildspec/build.sh

artifacts:
  files:
    - '**/*'
  base-directory: 'cloudformation'
  discard-paths: yes
