---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: 2010-09-09

Resources:
  RHELServer7UpdateComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name:  RHEL7-OS-Update
      Version: 0.0.1
      Description: Update all installed RPM's to latest hosted on RHUI
      ChangeDescription: Initial Release
      Platform: Linux
      SupportedOsVersions:
        - Red Hat Enterprise Linux 7 
      Data: |
        name: 'update_rhel_image'
        description: 'Updates the base rhel image to the latest patch release provided by RHUI'
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: update
                action: ExecuteBash
                onFailure: Abort
                inputs:
                  commands:
                    - |
                      sudo yum -y update
        
          - name: validate
            steps:
              - name: validateUpdate
                action: ExecuteBash
                inputs:
                  commands:
                    - |
                      REDHAT_MINOR_RELEASE=$(rpm -qi redhat-release-server | grep ^Version | awk -F: '{print $2}' | awk -F. '{print $2}' | sed 's/ //g')
        
                      function fail_with_message() {
                        1>&2 echo $1
                        exit 1
                      }
        
                      if [ -z "$REDHAT_MINOR_RELEASE" ]; then
                        fail_with_message "cannot determine os minor release, check if redhat-release-server package is installed correctly"
                      fi
        
                      if [ "$REDHAT_MINOR_RELEASE" -gt 5 ]; then
                        echo "OS has been updated"
                      else 
                        fail_with_message "OS version has not been updated"
                      fi